name: IDE Build and Upload

on:
  workflow_call:
    inputs:
      product:
        description: 'a product, available options: intellij_idea, pycharm'
        type: string
        required: true
      artifacts_dir:
        description: 'artifacts directory'
        type: string
        required: true
      version:
        type: string
        required: true

permissions: {}

jobs:
  distributions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/build_ide
        with:
          product: ${{inputs.product}}
          version: ${{inputs.version}}
      - name: upload-linux-x64
        uses: ./.github/actions/upload_ide
        with:
          os: linux
          suffix: .tar.gz
          artifacts_dir: ${{inputs.artifacts_dir}}
      - name: upload-linux-aarch64
        uses: ./.github/actions/upload_ide
        with:
          os: linux
          suffix: -aarch64.tar.gz
          artifacts_dir: ${{inputs.artifacts_dir}}
      - name: upload-windows-x64
        uses: ./.github/actions/upload_ide
        with:
          os: windows
          suffix: .exe
          artifacts_dir: ${{inputs.artifacts_dir}}
      - name: upload-mac-aarch64
        uses: ./.github/actions/upload_ide
        with:
          os: mac
          suffix: -aarch64.sit
          artifacts_dir: ${{inputs.artifacts_dir}}
      - name: upload-mac-x86
        uses: ./.github/actions/upload_ide
        with:
          os: mac
          suffix: .sit
          artifacts_dir: ${{inputs.artifacts_dir}}
      - name: Upload .dmg build scripts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: dmg-build-scripts
          if-no-files-found: 'error'
          retention-days: 1
          path: ${{inputs.artifacts_dir}}/macos-dmg-build/
  dmg:
    strategy:
      matrix:
        suffix:
          - '-aarch64'
          - ''
    runs-on: macos-latest
    needs: distributions
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Download .dmg build scripts
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: dmg-build-scripts
      - name: Download ${{ matrix.suffix }}.sit
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: mac${{ matrix.suffix }}.sit-unsigned
      - name: Build ${{ matrix.suffix }}.dmg
        shell: bash
        # language=bash
        run: /bin/bash ./build.sh
      - name: Upload .dmg
        uses: ./.github/actions/upload_ide
        with:
          os: mac
          suffix: ${{ matrix.suffix }}.dmg
          artifacts_dir: .
  build-appimage:
    strategy:
      matrix:
        # appimagetool expects a different format for the architecture so we need two variables
        arch:
          - suffix: ""
            appimage: x86_64
          - suffix: "-aarch64"
            appimage: aarch64
    runs-on: ubuntu-latest
    needs: distributions
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Download .tar.gz
        uses: actions/download-artifact@v4.1.8
        with:
          name: linux${{ matrix.arch.suffix }}.tar.gz-unsigned

      - name: Extract tar.gz
        run: |
          mkdir -p appdir/usr/bin
          tar -xzf *.tar.gz -C appdir/usr/ --strip-components=1

      - name: Prepare AppDir
        # language=bash
        run: |
          # AppRun file
          cat > appdir/AppRun <<'EOF'
          #!/bin/bash
          exec "$APPDIR/usr/bin/rebased" "$@"
          EOF
          chmod +x appdir/AppRun
          
          # Desktop file
          cat > appdir/rebased.desktop <<'EOF'
          [Desktop Entry]
          Name=Rebased
          Exec=AppRun
          Icon=rebased
          Type=Application
          Categories=Development;IDE;
          Terminal=false
          StartupWMClass=jetbrains-rebased
          StartupNotify=true
          X-AppImage-Version=${{inputs.version}}
          EOF
          
          # icon
          ln -s usr/bin/rebased.png appdir/rebased.png

      - name: Install appimagetool
        # this sucks. bash is the worst language ever made. appimagetool should be available on a package manager with lockfile support
        env:
          filename: "appimagetool-x86_64.AppImage"
          sha256: "ed4ce84f0d9caff66f50bcca6ff6f35aae54ce8135408b3fa33abfc3cb384eb0"
        # language=bash
        run: |
          set -euo pipefail # work properly flags! we don't want to risk running it even if the validation fails
          wget -q https://github.com/AppImage/appimagetool/releases/download/1.9.1/$filename
          echo "$sha256 $filename" | sha256sum -c
          chmod +x $filename
          mv $filename ./appimagetool

      - name: Build AppImage
        env:
          ARCH: ${{ matrix.arch.appimage }}
        # language=bash
        run: ./appimagetool appdir -u "gh-releases-zsync|$GITHUB_REPOSITORY_OWNER|rebased|latest|Rebased-${{ matrix.arch.appimage }}.AppImage.zsync"

      - name: Upload .AppImage
        uses: ./.github/actions/upload_ide
        with:
          os: linux
          suffix: -${{ matrix.arch.appimage }}.AppImage
          artifacts_dir: .