name: Publish to package managers
on:
  release:
    types: [released]
jobs:
  winget:
    runs-on: ubuntu-slim
    steps:
      - uses: vedantmgoyal9/winget-releaser@7bd472be23763def6e16bd06cc8b1cdfab0e2fd5
        with:
          identifier: detachhead.rebased
          token: ${{ secrets.WINGET_TOKEN }}
          installers-regex: ^rebased(-aarch64)?.exe$

  homebrew:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        repository: DetachHead/homebrew-tap
        persist-credentials: false
        submodules: true
    - name: bump cask pr
      env:
        # zizmor: ignore[secrets-outside-env] TODO
        HOMEBREW_GITHUB_API_TOKEN: "${{ secrets.HOMEBREW_TOKEN }}"
        version: ${{ github.event.release.tag_name }}
      run: |
        cd ./brew/bin
        ./brew tap detachhead/tap
        ./brew trust DetachHead/tap
        ./brew bump-cask-pr rebased --version $version
